// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

type SitemapChild struct {
	ID                 int64
	Url                string
	State              string
	Failures           int64
	RetryAt            int64
	ReferencesFound    int64
	ReferencesImported int64
	InvalidLocations   int64
	LastError          string
}

type SitemapRun struct {
	ID            int64
	State         string
	Force         int64
	IndexUrl      string
	IndexReady    int64
	IndexFailures int64
	StartedAt     int64
	FinishedAt    int64
	RetryAt       int64
	NextRequestAt int64
	LastError     string
}

type SitemapValidator struct {
	Url          string
	Etag         string
	LastModified string
	ResponseUrl  string
}
