// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
)

const addChild = `-- name: AddChild :exec
INSERT INTO sitemap_children (url) VALUES (?) ON CONFLICT (url) DO NOTHING
`

func (q *Queries) AddChild(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, addChild, url)
	return err
}

const addChildCounts = `-- name: AddChildCounts :exec
UPDATE sitemap_children SET references_found = references_found + ?1,
    references_imported = references_imported + ?2,
    invalid_locations = invalid_locations + ?3 WHERE id = ?4
`

type AddChildCountsParams struct {
	Found    int64
	Imported int64
	Invalid  int64
	ID       int64
}

func (q *Queries) AddChildCounts(ctx context.Context, arg AddChildCountsParams) error {
	_, err := q.db.ExecContext(ctx, addChildCounts,
		arg.Found,
		arg.Imported,
		arg.Invalid,
		arg.ID,
	)
	return err
}

const childCounts = `-- name: ChildCounts :one
SELECT COUNT(*) AS total,
    CAST(COALESCE(SUM(state = 'completed'), 0) AS INTEGER) AS completed,
    CAST(COALESCE(SUM(state = 'skipped'), 0) AS INTEGER) AS skipped,
    CAST(COALESCE(SUM(state = 'failed'), 0) AS INTEGER) AS failed,
    CAST(COALESCE(SUM(references_found), 0) AS INTEGER) AS found,
    CAST(COALESCE(SUM(references_imported), 0) AS INTEGER) AS imported,
    CAST(COALESCE(SUM(invalid_locations), 0) AS INTEGER) AS invalid
FROM sitemap_children
`

type ChildCountsRow struct {
	Total     int64
	Completed int64
	Skipped   int64
	Failed    int64
	Found     int64
	Imported  int64
	Invalid   int64
}

func (q *Queries) ChildCounts(ctx context.Context) (ChildCountsRow, error) {
	row := q.db.QueryRowContext(ctx, childCounts)
	var i ChildCountsRow
	err := row.Scan(
		&i.Total,
		&i.Completed,
		&i.Skipped,
		&i.Failed,
		&i.Found,
		&i.Imported,
		&i.Invalid,
	)
	return i, err
}

const clearChildren = `-- name: ClearChildren :exec
DELETE FROM sitemap_children
`

func (q *Queries) ClearChildren(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearChildren)
	return err
}

const getRun = `-- name: GetRun :one
SELECT id, state, force, index_url, index_ready, index_failures, started_at, finished_at, retry_at, next_request_at, last_error FROM sitemap_run WHERE id = 1
`

func (q *Queries) GetRun(ctx context.Context) (SitemapRun, error) {
	row := q.db.QueryRowContext(ctx, getRun)
	var i SitemapRun
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Force,
		&i.IndexUrl,
		&i.IndexReady,
		&i.IndexFailures,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RetryAt,
		&i.NextRequestAt,
		&i.LastError,
	)
	return i, err
}

const getValidator = `-- name: GetValidator :one
SELECT url, etag, last_modified, response_url FROM sitemap_validators WHERE url = ?
`

func (q *Queries) GetValidator(ctx context.Context, url string) (SitemapValidator, error) {
	row := q.db.QueryRowContext(ctx, getValidator, url)
	var i SitemapValidator
	err := row.Scan(
		&i.Url,
		&i.Etag,
		&i.LastModified,
		&i.ResponseUrl,
	)
	return i, err
}

const nextChild = `-- name: NextChild :one
SELECT id, url, state, failures, retry_at, references_found, references_imported, invalid_locations, last_error FROM sitemap_children WHERE state = 'pending' ORDER BY retry_at, id LIMIT 1
`

func (q *Queries) NextChild(ctx context.Context) (SitemapChild, error) {
	row := q.db.QueryRowContext(ctx, nextChild)
	var i SitemapChild
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.State,
		&i.Failures,
		&i.RetryAt,
		&i.ReferencesFound,
		&i.ReferencesImported,
		&i.InvalidLocations,
		&i.LastError,
	)
	return i, err
}

const recoverChildren = `-- name: RecoverChildren :exec
UPDATE sitemap_children SET state = 'pending' WHERE state = 'running'
`

func (q *Queries) RecoverChildren(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverChildren)
	return err
}

const resetChildCounts = `-- name: ResetChildCounts :exec
UPDATE sitemap_children SET references_found = 0, invalid_locations = 0 WHERE id = ?
`

func (q *Queries) ResetChildCounts(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetChildCounts, id)
	return err
}

const retryChildren = `-- name: RetryChildren :exec
UPDATE sitemap_children SET state = 'pending', failures = 0, retry_at = 0, last_error = ''
WHERE state IN ('pending', 'failed', 'running')
`

func (q *Queries) RetryChildren(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, retryChildren)
	return err
}

const saveGalleryRef = `-- name: SaveGalleryRef :execrows
INSERT INTO gallery_refs (gallery_id, token, metadata_priority) VALUES (?, ?, 1)
ON CONFLICT (gallery_id) DO NOTHING
`

type SaveGalleryRefParams struct {
	GalleryID int64
	Token     string
}

func (q *Queries) SaveGalleryRef(ctx context.Context, arg SaveGalleryRefParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveGalleryRef, arg.GalleryID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveValidator = `-- name: SaveValidator :exec
INSERT INTO sitemap_validators (url, etag, last_modified, response_url) VALUES (?, ?, ?, ?)
ON CONFLICT (url) DO UPDATE SET etag = excluded.etag, last_modified = excluded.last_modified,
    response_url = excluded.response_url
`

type SaveValidatorParams struct {
	Url          string
	Etag         string
	LastModified string
	ResponseUrl  string
}

func (q *Queries) SaveValidator(ctx context.Context, arg SaveValidatorParams) error {
	_, err := q.db.ExecContext(ctx, saveValidator,
		arg.Url,
		arg.Etag,
		arg.LastModified,
		arg.ResponseUrl,
	)
	return err
}

const updateChild = `-- name: UpdateChild :exec
UPDATE sitemap_children SET state = ?, failures = ?, retry_at = ?, last_error = ? WHERE id = ?
`

type UpdateChildParams struct {
	State     string
	Failures  int64
	RetryAt   int64
	LastError string
	ID        int64
}

func (q *Queries) UpdateChild(ctx context.Context, arg UpdateChildParams) error {
	_, err := q.db.ExecContext(ctx, updateChild,
		arg.State,
		arg.Failures,
		arg.RetryAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const updateRun = `-- name: UpdateRun :exec
UPDATE sitemap_run SET state = ?, force = ?, index_url = ?, index_ready = ?, index_failures = ?,
    started_at = ?, finished_at = ?, retry_at = ?, next_request_at = ?, last_error = ? WHERE id = 1
`

type UpdateRunParams struct {
	State         string
	Force         int64
	IndexUrl      string
	IndexReady    int64
	IndexFailures int64
	StartedAt     int64
	FinishedAt    int64
	RetryAt       int64
	NextRequestAt int64
	LastError     string
}

func (q *Queries) UpdateRun(ctx context.Context, arg UpdateRunParams) error {
	_, err := q.db.ExecContext(ctx, updateRun,
		arg.State,
		arg.Force,
		arg.IndexUrl,
		arg.IndexReady,
		arg.IndexFailures,
		arg.StartedAt,
		arg.FinishedAt,
		arg.RetryAt,
		arg.NextRequestAt,
		arg.LastError,
	)
	return err
}
