// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
)

const countDownloadsByState = `-- name: CountDownloadsByState :many
SELECT state, count(*) AS count FROM panda_downloads GROUP BY state
`

type CountDownloadsByStateRow struct {
	State string
	Count int64
}

func (q *Queries) CountDownloadsByState(ctx context.Context) ([]CountDownloadsByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, countDownloadsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDownloadsByStateRow{}
	for rows.Next() {
		var i CountDownloadsByStateRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDownload = `-- name: DeleteDownload :exec
DELETE FROM panda_downloads WHERE gallery_id = ?
`

func (q *Queries) DeleteDownload(ctx context.Context, galleryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDownload, galleryID)
	return err
}

const enqueueDownload = `-- name: EnqueueDownload :execrows
INSERT INTO panda_downloads (gallery_id, token, state, created_at, updated_at)
VALUES (?, ?, 'queued', ?, ?) ON CONFLICT (gallery_id) DO NOTHING
`

type EnqueueDownloadParams struct {
	GalleryID int64
	Token     string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) EnqueueDownload(ctx context.Context, arg EnqueueDownloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, enqueueDownload,
		arg.GalleryID,
		arg.Token,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDownload = `-- name: GetDownload :one
SELECT gallery_id, token, state, created_at, updated_at, retry_at, failures, size_bytes, last_error, expected_size_bytes FROM panda_downloads WHERE gallery_id = ?
`

func (q *Queries) GetDownload(ctx context.Context, galleryID int64) (PandaDownload, error) {
	row := q.db.QueryRowContext(ctx, getDownload, galleryID)
	var i PandaDownload
	err := row.Scan(
		&i.GalleryID,
		&i.Token,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryAt,
		&i.Failures,
		&i.SizeBytes,
		&i.LastError,
		&i.ExpectedSizeBytes,
	)
	return i, err
}

const getDownloadStorage = `-- name: GetDownloadStorage :one
SELECT id, reason, archive_bytes, gallery_id FROM panda_download_storage WHERE id = 1
`

func (q *Queries) GetDownloadStorage(ctx context.Context) (PandaDownloadStorage, error) {
	row := q.db.QueryRowContext(ctx, getDownloadStorage)
	var i PandaDownloadStorage
	err := row.Scan(
		&i.ID,
		&i.Reason,
		&i.ArchiveBytes,
		&i.GalleryID,
	)
	return i, err
}

const listDownloads = `-- name: ListDownloads :many
SELECT gallery_id, token, state, created_at, updated_at, retry_at, failures, size_bytes, last_error, expected_size_bytes FROM panda_downloads
WHERE CAST(?1 AS TEXT) = '' OR state = ?1
ORDER BY created_at DESC, gallery_id DESC LIMIT ?3 OFFSET ?2
`

type ListDownloadsParams struct {
	State      string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) ListDownloads(ctx context.Context, arg ListDownloadsParams) ([]PandaDownload, error) {
	rows, err := q.db.QueryContext(ctx, listDownloads, arg.State, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PandaDownload{}
	for rows.Next() {
		var i PandaDownload
		if err := rows.Scan(
			&i.GalleryID,
			&i.Token,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryAt,
			&i.Failures,
			&i.SizeBytes,
			&i.LastError,
			&i.ExpectedSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDownload = `-- name: NextDownload :one
SELECT gallery_id, token, state, created_at, updated_at, retry_at, failures, size_bytes, last_error, expected_size_bytes FROM panda_downloads WHERE state = 'queued' AND retry_at <= ?
ORDER BY created_at, gallery_id LIMIT 1
`

func (q *Queries) NextDownload(ctx context.Context, retryAt int64) (PandaDownload, error) {
	row := q.db.QueryRowContext(ctx, nextDownload, retryAt)
	var i PandaDownload
	err := row.Scan(
		&i.GalleryID,
		&i.Token,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RetryAt,
		&i.Failures,
		&i.SizeBytes,
		&i.LastError,
		&i.ExpectedSizeBytes,
	)
	return i, err
}

const recoverDownloads = `-- name: RecoverDownloads :many
SELECT gallery_id, token, state, created_at, updated_at, retry_at, failures, size_bytes, last_error, expected_size_bytes FROM panda_downloads WHERE state IN ('running', 'cancelled', 'deleting')
`

func (q *Queries) RecoverDownloads(ctx context.Context) ([]PandaDownload, error) {
	rows, err := q.db.QueryContext(ctx, recoverDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PandaDownload{}
	for rows.Next() {
		var i PandaDownload
		if err := rows.Scan(
			&i.GalleryID,
			&i.Token,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RetryAt,
			&i.Failures,
			&i.SizeBytes,
			&i.LastError,
			&i.ExpectedSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDownloadExpectedSize = `-- name: SetDownloadExpectedSize :exec
UPDATE panda_downloads SET expected_size_bytes = ?, updated_at = ? WHERE gallery_id = ?
`

type SetDownloadExpectedSizeParams struct {
	ExpectedSizeBytes int64
	UpdatedAt         int64
	GalleryID         int64
}

func (q *Queries) SetDownloadExpectedSize(ctx context.Context, arg SetDownloadExpectedSizeParams) error {
	_, err := q.db.ExecContext(ctx, setDownloadExpectedSize, arg.ExpectedSizeBytes, arg.UpdatedAt, arg.GalleryID)
	return err
}

const updateDownload = `-- name: UpdateDownload :exec
UPDATE panda_downloads SET state = ?, updated_at = ?, retry_at = ?, failures = ?,
    size_bytes = ?, last_error = ? WHERE gallery_id = ?
`

type UpdateDownloadParams struct {
	State     string
	UpdatedAt int64
	RetryAt   int64
	Failures  int64
	SizeBytes int64
	LastError string
	GalleryID int64
}

func (q *Queries) UpdateDownload(ctx context.Context, arg UpdateDownloadParams) error {
	_, err := q.db.ExecContext(ctx, updateDownload,
		arg.State,
		arg.UpdatedAt,
		arg.RetryAt,
		arg.Failures,
		arg.SizeBytes,
		arg.LastError,
		arg.GalleryID,
	)
	return err
}

const updateDownloadStorage = `-- name: UpdateDownloadStorage :exec
UPDATE panda_download_storage SET reason = ?, archive_bytes = ?, gallery_id = ? WHERE id = 1
`

type UpdateDownloadStorageParams struct {
	Reason       string
	ArchiveBytes int64
	GalleryID    int64
}

func (q *Queries) UpdateDownloadStorage(ctx context.Context, arg UpdateDownloadStorageParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadStorage, arg.Reason, arg.ArchiveBytes, arg.GalleryID)
	return err
}
