// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const createGallery = `-- name: CreateGallery :one
INSERT INTO galleries (title, source_id) VALUES (?, ?) RETURNING id, title, source_id
`

type CreateGalleryParams struct {
	Title    string
	SourceID sql.NullInt64
}

func (q *Queries) CreateGallery(ctx context.Context, arg CreateGalleryParams) (Gallery, error) {
	row := q.db.QueryRowContext(ctx, createGallery, arg.Title, arg.SourceID)
	var i Gallery
	err := row.Scan(&i.ID, &i.Title, &i.SourceID)
	return i, err
}

const createGalleryPage = `-- name: CreateGalleryPage :exec
INSERT INTO gallery_pages (gallery_id, position, source_file_id) VALUES (?, ?, ?)
`

type CreateGalleryPageParams struct {
	GalleryID    int64
	Position     int64
	SourceFileID int64
}

func (q *Queries) CreateGalleryPage(ctx context.Context, arg CreateGalleryPageParams) error {
	_, err := q.db.ExecContext(ctx, createGalleryPage, arg.GalleryID, arg.Position, arg.SourceFileID)
	return err
}

const deleteGallery = `-- name: DeleteGallery :exec
DELETE FROM galleries WHERE id = ?
`

func (q *Queries) DeleteGallery(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGallery, id)
	return err
}

const deleteGalleryPages = `-- name: DeleteGalleryPages :exec
DELETE FROM gallery_pages WHERE gallery_id = ?
`

func (q *Queries) DeleteGalleryPages(ctx context.Context, galleryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteGalleryPages, galleryID)
	return err
}

const getGallery = `-- name: GetGallery :one
SELECT id, title, source_id FROM galleries WHERE id = ?
`

func (q *Queries) GetGallery(ctx context.Context, id int64) (Gallery, error) {
	row := q.db.QueryRowContext(ctx, getGallery, id)
	var i Gallery
	err := row.Scan(&i.ID, &i.Title, &i.SourceID)
	return i, err
}

const getGalleryImageLocation = `-- name: GetGalleryImageLocation :one
SELECT l.path AS library_path, s.path AS source_path, s.kind, f.path AS file_path
FROM gallery_pages p
JOIN source_files f ON f.id = p.source_file_id
JOIN sources s ON s.id = f.source_id
JOIN libraries l ON l.id = s.library_id
WHERE p.gallery_id = ? ORDER BY p.position LIMIT 1 OFFSET ?
`

type GetGalleryImageLocationParams struct {
	GalleryID int64
	Offset    int64
}

type GetGalleryImageLocationRow struct {
	LibraryPath string
	SourcePath  string
	Kind        string
	FilePath    string
}

func (q *Queries) GetGalleryImageLocation(ctx context.Context, arg GetGalleryImageLocationParams) (GetGalleryImageLocationRow, error) {
	row := q.db.QueryRowContext(ctx, getGalleryImageLocation, arg.GalleryID, arg.Offset)
	var i GetGalleryImageLocationRow
	err := row.Scan(
		&i.LibraryPath,
		&i.SourcePath,
		&i.Kind,
		&i.FilePath,
	)
	return i, err
}

const getGallerySummary = `-- name: GetGallerySummary :one
SELECT g.id, g.title, count(p.position) AS page_count
FROM galleries g LEFT JOIN gallery_pages p ON p.gallery_id = g.id
WHERE g.id = ? GROUP BY g.id
`

type GetGallerySummaryRow struct {
	ID        int64
	Title     string
	PageCount int64
}

func (q *Queries) GetGallerySummary(ctx context.Context, id int64) (GetGallerySummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getGallerySummary, id)
	var i GetGallerySummaryRow
	err := row.Scan(&i.ID, &i.Title, &i.PageCount)
	return i, err
}

const getSourceFilePath = `-- name: GetSourceFilePath :one
SELECT path FROM source_files WHERE id = ?
`

func (q *Queries) GetSourceFilePath(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getSourceFilePath, id)
	var path string
	err := row.Scan(&path)
	return path, err
}

const getSourceTitle = `-- name: GetSourceTitle :one
SELECT sources.path, sources.kind, libraries.path AS library_path
FROM sources JOIN libraries ON libraries.id = sources.library_id
WHERE sources.id = ?
`

type GetSourceTitleRow struct {
	Path        string
	Kind        string
	LibraryPath string
}

func (q *Queries) GetSourceTitle(ctx context.Context, id int64) (GetSourceTitleRow, error) {
	row := q.db.QueryRowContext(ctx, getSourceTitle, id)
	var i GetSourceTitleRow
	err := row.Scan(&i.Path, &i.Kind, &i.LibraryPath)
	return i, err
}

const listGalleries = `-- name: ListGalleries :many
SELECT id, title, source_id FROM galleries ORDER BY title, id
`

func (q *Queries) ListGalleries(ctx context.Context) ([]Gallery, error) {
	rows, err := q.db.QueryContext(ctx, listGalleries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gallery{}
	for rows.Next() {
		var i Gallery
		if err := rows.Scan(&i.ID, &i.Title, &i.SourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGalleryPages = `-- name: ListGalleryPages :many
SELECT gallery_id, source_file_id,
       CAST(row_number() OVER (ORDER BY position) AS INTEGER) AS page_number
FROM gallery_pages WHERE gallery_id = ? ORDER BY position
`

type ListGalleryPagesRow struct {
	GalleryID    int64
	SourceFileID int64
	PageNumber   int64
}

func (q *Queries) ListGalleryPages(ctx context.Context, galleryID int64) ([]ListGalleryPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGalleryPages, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGalleryPagesRow{}
	for rows.Next() {
		var i ListGalleryPagesRow
		if err := rows.Scan(&i.GalleryID, &i.SourceFileID, &i.PageNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceFilesForGallery = `-- name: ListSourceFilesForGallery :many
SELECT id, path FROM source_files WHERE source_id = ?
`

type ListSourceFilesForGalleryRow struct {
	ID   int64
	Path string
}

func (q *Queries) ListSourceFilesForGallery(ctx context.Context, sourceID int64) ([]ListSourceFilesForGalleryRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceFilesForGallery, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceFilesForGalleryRow{}
	for rows.Next() {
		var i ListSourceFilesForGalleryRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameGallery = `-- name: RenameGallery :one
UPDATE galleries SET title = ? WHERE id = ? RETURNING id, title, source_id
`

type RenameGalleryParams struct {
	Title string
	ID    int64
}

func (q *Queries) RenameGallery(ctx context.Context, arg RenameGalleryParams) (Gallery, error) {
	row := q.db.QueryRowContext(ctx, renameGallery, arg.Title, arg.ID)
	var i Gallery
	err := row.Scan(&i.ID, &i.Title, &i.SourceID)
	return i, err
}
