// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
)

const createGallery = `-- name: CreateGallery :one
INSERT INTO galleries (id, title) VALUES (?, ?) RETURNING id, title
`

type CreateGalleryParams struct {
	ID    string
	Title string
}

func (q *Queries) CreateGallery(ctx context.Context, arg CreateGalleryParams) (Gallery, error) {
	row := q.db.QueryRowContext(ctx, createGallery, arg.ID, arg.Title)
	var i Gallery
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const createGalleryPage = `-- name: CreateGalleryPage :exec
INSERT INTO gallery_pages (gallery_id, position, source_file_id) VALUES (?, ?, ?)
`

type CreateGalleryPageParams struct {
	GalleryID    string
	Position     int64
	SourceFileID string
}

func (q *Queries) CreateGalleryPage(ctx context.Context, arg CreateGalleryPageParams) error {
	_, err := q.db.ExecContext(ctx, createGalleryPage, arg.GalleryID, arg.Position, arg.SourceFileID)
	return err
}

const deleteGallery = `-- name: DeleteGallery :exec
DELETE FROM galleries WHERE id = ?
`

func (q *Queries) DeleteGallery(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGallery, id)
	return err
}

const deleteGalleryPages = `-- name: DeleteGalleryPages :exec
DELETE FROM gallery_pages WHERE gallery_id = ?
`

func (q *Queries) DeleteGalleryPages(ctx context.Context, galleryID string) error {
	_, err := q.db.ExecContext(ctx, deleteGalleryPages, galleryID)
	return err
}

const getGallery = `-- name: GetGallery :one
SELECT id, title FROM galleries WHERE id = ?
`

func (q *Queries) GetGallery(ctx context.Context, id string) (Gallery, error) {
	row := q.db.QueryRowContext(ctx, getGallery, id)
	var i Gallery
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getSourceFilePath = `-- name: GetSourceFilePath :one
SELECT path FROM source_files WHERE id = ?
`

func (q *Queries) GetSourceFilePath(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSourceFilePath, id)
	var path string
	err := row.Scan(&path)
	return path, err
}

const getSourceTitle = `-- name: GetSourceTitle :one
SELECT sources.path, sources.kind, libraries.path AS library_path
FROM sources JOIN libraries ON libraries.id = sources.library_id
WHERE sources.id = ?
`

type GetSourceTitleRow struct {
	Path        string
	Kind        string
	LibraryPath string
}

func (q *Queries) GetSourceTitle(ctx context.Context, id string) (GetSourceTitleRow, error) {
	row := q.db.QueryRowContext(ctx, getSourceTitle, id)
	var i GetSourceTitleRow
	err := row.Scan(&i.Path, &i.Kind, &i.LibraryPath)
	return i, err
}

const listGalleries = `-- name: ListGalleries :many
SELECT id, title FROM galleries ORDER BY title, id
`

func (q *Queries) ListGalleries(ctx context.Context) ([]Gallery, error) {
	rows, err := q.db.QueryContext(ctx, listGalleries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gallery{}
	for rows.Next() {
		var i Gallery
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGalleryPages = `-- name: ListGalleryPages :many
SELECT gallery_id, source_file_id,
       CAST(row_number() OVER (ORDER BY position) AS INTEGER) AS page_number
FROM gallery_pages WHERE gallery_id = ? ORDER BY position
`

type ListGalleryPagesRow struct {
	GalleryID    string
	SourceFileID string
	PageNumber   int64
}

func (q *Queries) ListGalleryPages(ctx context.Context, galleryID string) ([]ListGalleryPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGalleryPages, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGalleryPagesRow{}
	for rows.Next() {
		var i ListGalleryPagesRow
		if err := rows.Scan(&i.GalleryID, &i.SourceFileID, &i.PageNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceFilesForGallery = `-- name: ListSourceFilesForGallery :many
SELECT id, path FROM source_files WHERE source_id = ?
`

type ListSourceFilesForGalleryRow struct {
	ID   string
	Path string
}

func (q *Queries) ListSourceFilesForGallery(ctx context.Context, sourceID string) ([]ListSourceFilesForGalleryRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceFilesForGallery, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceFilesForGalleryRow{}
	for rows.Next() {
		var i ListSourceFilesForGalleryRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameGallery = `-- name: RenameGallery :one
UPDATE galleries SET title = ? WHERE id = ? RETURNING id, title
`

type RenameGalleryParams struct {
	Title string
	ID    string
}

func (q *Queries) RenameGallery(ctx context.Context, arg RenameGalleryParams) (Gallery, error) {
	row := q.db.QueryRowContext(ctx, renameGallery, arg.Title, arg.ID)
	var i Gallery
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}
