// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const attachFetch = `-- name: AttachFetch :exec
INSERT INTO metadata_fetch_job_entries (job_id, position, fetch_id) VALUES (?, ?, ?)
`

type AttachFetchParams struct {
	JobID    string
	Position int64
	FetchID  int64
}

func (q *Queries) AttachFetch(ctx context.Context, arg AttachFetchParams) error {
	_, err := q.db.ExecContext(ctx, attachFetch, arg.JobID, arg.Position, arg.FetchID)
	return err
}

const completeFetch = `-- name: CompleteFetch :exec
UPDATE metadata_fetches SET status = ?, error = ?, refreshed_at = ?
WHERE gallery_id = ? AND token = ? AND status = 'pending'
`

type CompleteFetchParams struct {
	Status      string
	Error       string
	RefreshedAt sql.NullInt64
	GalleryID   int64
	Token       string
}

func (q *Queries) CompleteFetch(ctx context.Context, arg CompleteFetchParams) error {
	_, err := q.db.ExecContext(ctx, completeFetch,
		arg.Status,
		arg.Error,
		arg.RefreshedAt,
		arg.GalleryID,
		arg.Token,
	)
	return err
}

const completeFetchJobs = `-- name: CompleteFetchJobs :exec
UPDATE metadata_fetch_jobs SET completed_at = ?
WHERE completed_at IS NULL AND NOT EXISTS (
    SELECT 1 FROM metadata_fetch_job_entries e JOIN metadata_fetches f ON f.id = e.fetch_id
    WHERE e.job_id = metadata_fetch_jobs.id AND f.status = 'pending'
)
`

func (q *Queries) CompleteFetchJobs(ctx context.Context, completedAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, completeFetchJobs, completedAt)
	return err
}

const createFetch = `-- name: CreateFetch :one
INSERT INTO metadata_fetches (gallery_id, token, status, error) VALUES (?, ?, ?, ?) RETURNING id
`

type CreateFetchParams struct {
	GalleryID int64
	Token     string
	Status    string
	Error     string
}

func (q *Queries) CreateFetch(ctx context.Context, arg CreateFetchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createFetch,
		arg.GalleryID,
		arg.Token,
		arg.Status,
		arg.Error,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createFetchJob = `-- name: CreateFetchJob :exec
INSERT INTO metadata_fetch_jobs (id, created_at) VALUES (?, ?)
`

type CreateFetchJobParams struct {
	ID        string
	CreatedAt int64
}

func (q *Queries) CreateFetchJob(ctx context.Context, arg CreateFetchJobParams) error {
	_, err := q.db.ExecContext(ctx, createFetchJob, arg.ID, arg.CreatedAt)
	return err
}

const deleteExpiredFetchJobs = `-- name: DeleteExpiredFetchJobs :exec
DELETE FROM metadata_fetch_jobs WHERE completed_at <= ?
`

func (q *Queries) DeleteExpiredFetchJobs(ctx context.Context, completedAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredFetchJobs, completedAt)
	return err
}

const deleteOrphanFetches = `-- name: DeleteOrphanFetches :exec
DELETE FROM metadata_fetches WHERE status != 'pending' AND NOT EXISTS (
    SELECT 1 FROM metadata_fetch_job_entries e WHERE e.fetch_id = metadata_fetches.id
)
`

func (q *Queries) DeleteOrphanFetches(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanFetches)
	return err
}

const failConflictingFetches = `-- name: FailConflictingFetches :exec
UPDATE metadata_fetches SET status = 'failed', error = 'token_conflict'
WHERE status = 'pending' AND EXISTS (
    SELECT 1 FROM gallery_refs r WHERE r.gallery_id = metadata_fetches.gallery_id AND r.token != metadata_fetches.token
)
`

func (q *Queries) FailConflictingFetches(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, failConflictingFetches)
	return err
}

const fetchJobEntries = `-- name: FetchJobEntries :many
SELECT f.gallery_id, f.status, f.error, f.refreshed_at
FROM metadata_fetch_job_entries e JOIN metadata_fetches f ON f.id = e.fetch_id
WHERE e.job_id = ? ORDER BY e.position
`

type FetchJobEntriesRow struct {
	GalleryID   int64
	Status      string
	Error       string
	RefreshedAt sql.NullInt64
}

func (q *Queries) FetchJobEntries(ctx context.Context, jobID string) ([]FetchJobEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchJobEntries, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchJobEntriesRow{}
	for rows.Next() {
		var i FetchJobEntriesRow
		if err := rows.Scan(
			&i.GalleryID,
			&i.Status,
			&i.Error,
			&i.RefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPendingFetch = `-- name: FindPendingFetch :one
SELECT id FROM metadata_fetches WHERE gallery_id = ? AND token = ? AND status = 'pending'
`

type FindPendingFetchParams struct {
	GalleryID int64
	Token     string
}

func (q *Queries) FindPendingFetch(ctx context.Context, arg FindPendingFetchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findPendingFetch, arg.GalleryID, arg.Token)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getFetchJob = `-- name: GetFetchJob :one
SELECT id, created_at, completed_at FROM metadata_fetch_jobs
WHERE id = ? AND (completed_at IS NULL OR completed_at > ?2)
`

type GetFetchJobParams struct {
	ID     string
	Cutoff sql.NullInt64
}

func (q *Queries) GetFetchJob(ctx context.Context, arg GetFetchJobParams) (MetadataFetchJob, error) {
	row := q.db.QueryRowContext(ctx, getFetchJob, arg.ID, arg.Cutoff)
	var i MetadataFetchJob
	err := row.Scan(&i.ID, &i.CreatedAt, &i.CompletedAt)
	return i, err
}

const getGalleryToken = `-- name: GetGalleryToken :one
SELECT token FROM gallery_refs WHERE gallery_id = ?
`

func (q *Queries) GetGalleryToken(ctx context.Context, galleryID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getGalleryToken, galleryID)
	var token string
	err := row.Scan(&token)
	return token, err
}

const getMetadata = `-- name: GetMetadata :one
SELECT body, refreshed_at FROM gallery_metadata WHERE gallery_id = ?
`

type GetMetadataRow struct {
	Body        []byte
	RefreshedAt int64
}

func (q *Queries) GetMetadata(ctx context.Context, galleryID int64) (GetMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, galleryID)
	var i GetMetadataRow
	err := row.Scan(&i.Body, &i.RefreshedAt)
	return i, err
}

const lookupMetadata = `-- name: LookupMetadata :one
SELECT m.body, m.refreshed_at, r.metadata_attempted_at,
    EXISTS (SELECT 1 FROM metadata_fetches f
            WHERE f.gallery_id = r.gallery_id AND f.token = r.token AND f.status = 'pending') AS pending_fetch
FROM gallery_refs r LEFT JOIN gallery_metadata m ON m.gallery_id = r.gallery_id
WHERE r.gallery_id = ?
`

type LookupMetadataRow struct {
	Body                []byte
	RefreshedAt         sql.NullInt64
	MetadataAttemptedAt sql.NullInt64
	PendingFetch        int64
}

func (q *Queries) LookupMetadata(ctx context.Context, galleryID int64) (LookupMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, lookupMetadata, galleryID)
	var i LookupMetadataRow
	err := row.Scan(
		&i.Body,
		&i.RefreshedAt,
		&i.MetadataAttemptedAt,
		&i.PendingFetch,
	)
	return i, err
}

const pendingFetches = `-- name: PendingFetches :many
SELECT f.gallery_id, f.token FROM metadata_fetches f
WHERE f.status = 'pending' AND NOT EXISTS (
    SELECT 1 FROM metadata_fetches older
    WHERE older.gallery_id = f.gallery_id AND older.status = 'pending' AND older.id < f.id
) ORDER BY f.id LIMIT ?
`

type PendingFetchesRow struct {
	GalleryID int64
	Token     string
}

func (q *Queries) PendingFetches(ctx context.Context, limit int64) ([]PendingFetchesRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingFetches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingFetchesRow{}
	for rows.Next() {
		var i PendingFetchesRow
		if err := rows.Scan(&i.GalleryID, &i.Token); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingRefs = `-- name: PendingRefs :many
SELECT gallery_id, token FROM gallery_refs WHERE metadata_attempted_at IS NULL
ORDER BY metadata_priority, gallery_id LIMIT ?
`

type PendingRefsRow struct {
	GalleryID int64
	Token     string
}

func (q *Queries) PendingRefs(ctx context.Context, limit int64) ([]PendingRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingRefs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingRefsRow{}
	for rows.Next() {
		var i PendingRefsRow
		if err := rows.Scan(&i.GalleryID, &i.Token); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAttempt = `-- name: RecordAttempt :exec
UPDATE gallery_refs SET metadata_attempted_at = ?, metadata_error = ? WHERE gallery_id = ? AND token = ?
`

type RecordAttemptParams struct {
	MetadataAttemptedAt sql.NullInt64
	MetadataError       sql.NullString
	GalleryID           int64
	Token               string
}

func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) error {
	_, err := q.db.ExecContext(ctx, recordAttempt,
		arg.MetadataAttemptedAt,
		arg.MetadataError,
		arg.GalleryID,
		arg.Token,
	)
	return err
}

const recordBatchFailure = `-- name: RecordBatchFailure :exec
UPDATE metadata_retry SET failures = ?, next_attempt_at = ?, last_attempt_at = ?, last_error = ? WHERE id = 1
`

type RecordBatchFailureParams struct {
	Failures      int64
	NextAttemptAt int64
	LastAttemptAt sql.NullInt64
	LastError     sql.NullString
}

func (q *Queries) RecordBatchFailure(ctx context.Context, arg RecordBatchFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordBatchFailure,
		arg.Failures,
		arg.NextAttemptAt,
		arg.LastAttemptAt,
		arg.LastError,
	)
	return err
}

const recordBatchSuccess = `-- name: RecordBatchSuccess :exec
UPDATE metadata_retry SET failures = 0, next_attempt_at = 0, last_attempt_at = ?, last_error = NULL WHERE id = 1
`

func (q *Queries) RecordBatchSuccess(ctx context.Context, lastAttemptAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, recordBatchSuccess, lastAttemptAt)
	return err
}

const retryState = `-- name: RetryState :one
SELECT failures, next_attempt_at FROM metadata_retry WHERE id = 1
`

type RetryStateRow struct {
	Failures      int64
	NextAttemptAt int64
}

func (q *Queries) RetryState(ctx context.Context) (RetryStateRow, error) {
	row := q.db.QueryRowContext(ctx, retryState)
	var i RetryStateRow
	err := row.Scan(&i.Failures, &i.NextAttemptAt)
	return i, err
}

const saveGalleryRef = `-- name: SaveGalleryRef :exec
INSERT INTO gallery_refs (gallery_id, token) VALUES (?, ?)
ON CONFLICT (gallery_id) DO UPDATE SET metadata_priority = 0
`

type SaveGalleryRefParams struct {
	GalleryID int64
	Token     string
}

func (q *Queries) SaveGalleryRef(ctx context.Context, arg SaveGalleryRefParams) error {
	_, err := q.db.ExecContext(ctx, saveGalleryRef, arg.GalleryID, arg.Token)
	return err
}

const saveMetadata = `-- name: SaveMetadata :exec
INSERT INTO gallery_metadata (gallery_id, body, refreshed_at) VALUES (?, ?, ?)
ON CONFLICT (gallery_id) DO UPDATE SET body = excluded.body, refreshed_at = excluded.refreshed_at
`

type SaveMetadataParams struct {
	GalleryID   int64
	Body        []byte
	RefreshedAt int64
}

func (q *Queries) SaveMetadata(ctx context.Context, arg SaveMetadataParams) error {
	_, err := q.db.ExecContext(ctx, saveMetadata, arg.GalleryID, arg.Body, arg.RefreshedAt)
	return err
}
