// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const getMetadata = `-- name: GetMetadata :one
SELECT body, refreshed_at FROM gallery_metadata WHERE gallery_id = ?
`

type GetMetadataRow struct {
	Body        []byte
	RefreshedAt int64
}

func (q *Queries) GetMetadata(ctx context.Context, galleryID int64) (GetMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, galleryID)
	var i GetMetadataRow
	err := row.Scan(&i.Body, &i.RefreshedAt)
	return i, err
}

const pendingRefs = `-- name: PendingRefs :many
SELECT gallery_id, token FROM gallery_refs WHERE metadata_attempted_at IS NULL ORDER BY gallery_id LIMIT ?
`

type PendingRefsRow struct {
	GalleryID int64
	Token     string
}

func (q *Queries) PendingRefs(ctx context.Context, limit int64) ([]PendingRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, pendingRefs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingRefsRow{}
	for rows.Next() {
		var i PendingRefsRow
		if err := rows.Scan(&i.GalleryID, &i.Token); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAttempt = `-- name: RecordAttempt :exec
UPDATE gallery_refs SET metadata_attempted_at = ?, metadata_error = ? WHERE gallery_id = ?
`

type RecordAttemptParams struct {
	MetadataAttemptedAt sql.NullInt64
	MetadataError       sql.NullString
	GalleryID           int64
}

func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) error {
	_, err := q.db.ExecContext(ctx, recordAttempt, arg.MetadataAttemptedAt, arg.MetadataError, arg.GalleryID)
	return err
}

const recordBatchFailure = `-- name: RecordBatchFailure :exec
UPDATE metadata_retry SET failures = ?, next_attempt_at = ?, last_attempt_at = ?, last_error = ? WHERE id = 1
`

type RecordBatchFailureParams struct {
	Failures      int64
	NextAttemptAt int64
	LastAttemptAt sql.NullInt64
	LastError     sql.NullString
}

func (q *Queries) RecordBatchFailure(ctx context.Context, arg RecordBatchFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordBatchFailure,
		arg.Failures,
		arg.NextAttemptAt,
		arg.LastAttemptAt,
		arg.LastError,
	)
	return err
}

const recordBatchSuccess = `-- name: RecordBatchSuccess :exec
UPDATE metadata_retry SET failures = 0, next_attempt_at = 0, last_attempt_at = ?, last_error = NULL WHERE id = 1
`

func (q *Queries) RecordBatchSuccess(ctx context.Context, lastAttemptAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, recordBatchSuccess, lastAttemptAt)
	return err
}

const retryState = `-- name: RetryState :one
SELECT failures, next_attempt_at FROM metadata_retry WHERE id = 1
`

type RetryStateRow struct {
	Failures      int64
	NextAttemptAt int64
}

func (q *Queries) RetryState(ctx context.Context) (RetryStateRow, error) {
	row := q.db.QueryRowContext(ctx, retryState)
	var i RetryStateRow
	err := row.Scan(&i.Failures, &i.NextAttemptAt)
	return i, err
}

const saveGalleryRef = `-- name: SaveGalleryRef :exec
INSERT INTO gallery_refs (gallery_id, token) VALUES (?, ?) ON CONFLICT (gallery_id) DO NOTHING
`

type SaveGalleryRefParams struct {
	GalleryID int64
	Token     string
}

func (q *Queries) SaveGalleryRef(ctx context.Context, arg SaveGalleryRefParams) error {
	_, err := q.db.ExecContext(ctx, saveGalleryRef, arg.GalleryID, arg.Token)
	return err
}

const saveMetadata = `-- name: SaveMetadata :exec
INSERT INTO gallery_metadata (gallery_id, body, refreshed_at) VALUES (?, ?, ?)
ON CONFLICT (gallery_id) DO UPDATE SET body = excluded.body, refreshed_at = excluded.refreshed_at
`

type SaveMetadataParams struct {
	GalleryID   int64
	Body        []byte
	RefreshedAt int64
}

func (q *Queries) SaveMetadata(ctx context.Context, arg SaveMetadataParams) error {
	_, err := q.db.ExecContext(ctx, saveMetadata, arg.GalleryID, arg.Body, arg.RefreshedAt)
	return err
}
