package httpapi

import (
	"net/http"

	"github.com/fuzzy-moose/tana/internal/local"
	"github.com/fuzzy-moose/tana/internal/server"
)

func NewHandler(app *local.App) http.Handler {
	mux := http.NewServeMux()
	mux.Handle("GET /api/collector/status", HandleCollectorStatus(app.Collector))
	mux.Handle("GET /api/collector/inventory/status", HandleCollectorInventoryStatus(app.Collector))
	mux.Handle("GET /api/collector/favorites/status", HandleCollectorFavoritesStatus(app.Collector))
	mux.Handle("GET /api/collector/metadata/status", HandleCollectorMetadataStatus(app.Collector))
	proxies := HandleCollectorMetadataProxies(app.Collector)
	mux.Handle("GET /api/collector/metadata/proxies", proxies)
	mux.Handle("PUT /api/collector/metadata/proxies", proxies)
	mux.Handle("POST /api/collector/metadata/proxies/import", HandleImportCollectorMetadataProxies(app.Collector))
	mux.Handle("POST /api/collector/metadata/proxies/channels", proxies)
	mux.Handle("PUT /api/collector/metadata/proxies/channels/{id}", proxies)
	mux.Handle("DELETE /api/collector/metadata/proxies/channels/{id}", proxies)
	mux.Handle("GET /api/collector/catalog", HandleCollectorCatalog(app.Collector))
	mux.Handle("GET /api/collector/catalog/completions", HandleCollectorCatalogCompletions(app.Collector))
	mux.Handle("POST /api/collector/catalog/lookup", HandleCollectorGalleryLookup(app.Collector))
	mux.Handle("GET /api/collector/metadata/fetches/{id}", HandleCollectorMetadataFetch(app.Collector))
	mux.Handle("GET /api/collector/feed/status", HandleCollectorFeed(app.Collector))
	mux.Handle("POST /api/collector/feed/refresh", HandleCollectorFeed(app.Collector))
	mux.Handle("GET /api/collector/feed/captures", HandleCollectorFeedCaptures(app.Collector))
	mux.Handle("GET /api/collector/feed/captures/{id}/file", HandleCollectorFeedCaptureFile(app.Collector))
	mux.Handle("GET /api/collector/sitemap/status", HandleCollectorSitemap(app.Collector))
	mux.Handle("POST /api/collector/sitemap/{action}", HandleCollectorSitemap(app.Collector))
	mux.Handle("POST /api/collector/favorites/{category}/sync", HandleCollectorSyncFavorites(app.Collector))
	mux.Handle("GET /api/collector/favorites/download-settings", HandleCollectorFavoriteDownloadSettings(app.Collector))
	mux.Handle("PUT /api/collector/favorites/download-settings", HandleCollectorFavoriteDownloadSettings(app.Collector))
	mux.Handle("POST /api/collector/favorites/{category}/missing-downloads/preview", HandlePreviewMissingFavoriteDownloads(app.FavoriteDownloads))
	mux.Handle("POST /api/collector/favorites/{category}/missing-downloads", HandleSubmitMissingFavoriteDownloads(app.FavoriteDownloads))
	mux.Handle("POST /api/collector/reference-imports", HandleCollectorSubmitReferenceImport(app.Collector))
	mux.Handle("GET /api/collector/reference-imports", HandleCollectorListReferenceImports(app.Collector))
	mux.Handle("GET /api/collector/reference-imports/{id}", HandleCollectorGetReferenceImport(app.Collector))
	mux.Handle("POST /api/collector/reference-imports/{id}/pause", HandleCollectorPauseReferenceImport(app.Collector))
	mux.Handle("POST /api/collector/reference-imports/{id}/resume", HandleCollectorResumeReferenceImport(app.Collector))
	mux.Handle("POST /api/collector/reference-imports/{id}/cancel", HandleCollectorCancelReferenceImport(app.Collector))
	mux.Handle("POST /api/collector/reference-imports/{id}/retry", HandleCollectorRetryReferenceImport(app.Collector))
	downloads := HandleCollectorDownloads(app.Collector)
	mux.Handle("/api/collector/downloads", downloads)
	mux.Handle("/api/collector/downloads/", downloads)
	deliveries := HandleLibraryDeliveries(app.Deliveries, app.Collector)
	mux.Handle("/api/library-deliveries", deliveries)
	mux.Handle("/api/library-deliveries/", deliveries)
	mux.Handle("GET /api/galleries", HandleListGalleries(app.Galleries))
	mux.Handle("GET /api/gallery-search/completions", HandleCompleteGallerySearch(app.Galleries))
	mux.Handle("GET /api/galleries/{id}", HandleGetGallery(app.Galleries))
	mux.Handle("GET /api/galleries/{id}/pages/{number}/image", HandleGalleryImage(app.Galleries))
	mux.Handle("POST /api/scans", HandleRequestScan(app.Scans))
	mux.Handle("GET /api/scans/status", HandleScanStatus(app.Scans))
	mux.Handle("GET /api/source-cleanup", HandlePreviewSourceCleanup(app.Cleanup))
	mux.Handle("POST /api/source-cleanup", HandleExecuteSourceCleanup(app.Cleanup))
	mux.Handle("POST /api/libraries", HandleCreateLibrary(app.Libraries))
	mux.Handle("GET /api/libraries", HandleListLibraries(app.Libraries))
	mux.Handle("GET /api/libraries/{id}", HandleGetLibrary(app.Libraries))
	mux.Handle("PATCH /api/libraries/{id}", HandleRenameLibrary(app.Libraries))
	mux.Handle("DELETE /api/libraries/{id}", HandleDeleteLibrary(app.Libraries))
	mux.Handle("POST /api/libraries/{id}/availability-check", HandleCheckLibraryAvailability(app.Libraries))
	mux.HandleFunc("GET /healthz", server.Health)

	root := http.NewServeMux()
	root.Handle("/api", mux)
	root.Handle("/api/", mux)
	root.Handle("/healthz", mux)
	if app.Web != nil {
		files := http.NewServeMux()
		files.Handle("GET /", http.FileServerFS(app.Web))
		root.Handle("/", files)
	}
	var handler http.Handler = root
	handler = server.CSRFMiddleware(handler)
	handler = server.LoggingMiddleware(app.Logger, handler)
	handler = server.HTTPContextMiddleware(handler)
	return handler
}
