// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
)

const banUntil = `-- name: BanUntil :one
SELECT until_at FROM panda_ban WHERE id = 1
`

func (q *Queries) BanUntil(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, banUntil)
	var until_at int64
	err := row.Scan(&until_at)
	return until_at, err
}

const extendBan = `-- name: ExtendBan :exec
UPDATE panda_ban SET until_at = MAX(until_at, CAST(?1 AS INTEGER)) WHERE id = 1
`

func (q *Queries) ExtendBan(ctx context.Context, untilAt int64) error {
	_, err := q.db.ExecContext(ctx, extendBan, untilAt)
	return err
}
