// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const inventoryStatistics = `-- name: InventoryStatistics :one
WITH counts AS (
    SELECT
        (SELECT count(*) FROM gallery_refs) AS gallery_references,
        (SELECT count(*) FROM gallery_metadata) AS metadata_available,
        (SELECT count(*) FROM gallery_refs r
         WHERE r.metadata_attempted_at IS NULL
         AND NOT EXISTS (SELECT 1 FROM gallery_metadata m INDEXED BY gallery_metadata_inventory WHERE m.gallery_id = r.gallery_id))
        + (SELECT count(*) FROM metadata_fetches f JOIN gallery_refs r ON r.gallery_id = f.gallery_id AND r.token = f.token
           WHERE f.status = 'pending' AND r.metadata_attempted_at IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM gallery_metadata m INDEXED BY gallery_metadata_inventory WHERE m.gallery_id = r.gallery_id)) AS metadata_pending
)
SELECT gallery_references, metadata_available, CAST(metadata_pending AS INTEGER) AS metadata_pending,
    CAST(gallery_references - metadata_available - metadata_pending AS INTEGER) AS metadata_failed,
    (SELECT count(*) FROM metadata_fetches WHERE status = 'pending') AS fetches_pending,
    (SELECT count(*) FROM metadata_fetches WHERE status = 'failed') AS fetches_failed
FROM counts
`

type InventoryStatisticsRow struct {
	GalleryReferences int64
	MetadataAvailable int64
	MetadataPending   int64
	MetadataFailed    int64
	FetchesPending    int64
	FetchesFailed     int64
}

func (q *Queries) InventoryStatistics(ctx context.Context) (InventoryStatisticsRow, error) {
	row := q.db.QueryRowContext(ctx, inventoryStatistics)
	var i InventoryStatisticsRow
	err := row.Scan(
		&i.GalleryReferences,
		&i.MetadataAvailable,
		&i.MetadataPending,
		&i.MetadataFailed,
		&i.FetchesPending,
		&i.FetchesFailed,
	)
	return i, err
}

const metadataRetry = `-- name: MetadataRetry :one
SELECT next_attempt_at, last_error,
    (SELECT main_background_paused FROM metadata_collection_settings WHERE id = 1) AS main_background_paused
FROM metadata_retry WHERE id = 1
`

type MetadataRetryRow struct {
	NextAttemptAt        int64
	LastError            sql.NullString
	MainBackgroundPaused int64
}

func (q *Queries) MetadataRetry(ctx context.Context) (MetadataRetryRow, error) {
	row := q.db.QueryRowContext(ctx, metadataRetry)
	var i MetadataRetryRow
	err := row.Scan(&i.NextAttemptAt, &i.LastError, &i.MainBackgroundPaused)
	return i, err
}

const recentMetadataErrors = `-- name: RecentMetadataErrors :many
WITH gallery_errors AS (
    SELECT gallery_id, metadata_error, metadata_attempted_at
    FROM gallery_refs WHERE metadata_error IS NOT NULL AND metadata_error != ''
    ORDER BY metadata_attempted_at DESC, gallery_id LIMIT 10
), errors AS (
    SELECT gallery_id, metadata_error, metadata_attempted_at FROM gallery_errors
    UNION ALL
    SELECT f.gallery_id, f.error, (
        SELECT max(coalesce(j.completed_at, j.created_at))
        FROM metadata_fetch_job_entries e JOIN metadata_fetch_jobs j ON j.id = e.job_id
        WHERE e.fetch_id = f.id
    ) AS metadata_attempted_at
    FROM metadata_fetches f WHERE f.status = 'failed'
), latest AS (
    SELECT gallery_id, metadata_error, metadata_attempted_at, row_number() OVER (PARTITION BY gallery_id ORDER BY metadata_attempted_at DESC) AS position
    FROM errors
)
SELECT gallery_id, metadata_error, metadata_attempted_at FROM latest WHERE position = 1
ORDER BY metadata_attempted_at DESC, gallery_id LIMIT 10
`

type RecentMetadataErrorsRow struct {
	GalleryID           int64
	MetadataError       sql.NullString
	MetadataAttemptedAt sql.NullInt64
}

func (q *Queries) RecentMetadataErrors(ctx context.Context) ([]RecentMetadataErrorsRow, error) {
	rows, err := q.db.QueryContext(ctx, recentMetadataErrors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentMetadataErrorsRow{}
	for rows.Next() {
		var i RecentMetadataErrorsRow
		if err := rows.Scan(&i.GalleryID, &i.MetadataError, &i.MetadataAttemptedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
