// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

type FeedContinuityCheck struct {
	PreviousCaptureID int64
	CurrentCaptureID  int64
	Status            string
	CreatedAt         int64
	CheckedAt         int64
}
