// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const captureBody = `-- name: CaptureBody :one
SELECT body FROM raw_feeds WHERE id = ?
`

func (q *Queries) CaptureBody(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, captureBody, id)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const completeContinuityCheck = `-- name: CompleteContinuityCheck :one
UPDATE feed_continuity_checks SET status = ?, checked_at = ?
WHERE current_capture_id = ? RETURNING previous_capture_id, current_capture_id, status, created_at, checked_at
`

type CompleteContinuityCheckParams struct {
	Status           string
	CheckedAt        int64
	CurrentCaptureID int64
}

func (q *Queries) CompleteContinuityCheck(ctx context.Context, arg CompleteContinuityCheckParams) (FeedContinuityCheck, error) {
	row := q.db.QueryRowContext(ctx, completeContinuityCheck, arg.Status, arg.CheckedAt, arg.CurrentCaptureID)
	var i FeedContinuityCheck
	err := row.Scan(
		&i.PreviousCaptureID,
		&i.CurrentCaptureID,
		&i.Status,
		&i.CreatedAt,
		&i.CheckedAt,
	)
	return i, err
}

const createContinuityCheck = `-- name: CreateContinuityCheck :exec
INSERT INTO feed_continuity_checks
    (previous_capture_id, current_capture_id, status, created_at, checked_at)
VALUES (?1, ?2, 'unknown', ?3, ?3)
`

type CreateContinuityCheckParams struct {
	PreviousCaptureID int64
	CurrentCaptureID  int64
	Now               int64
}

func (q *Queries) CreateContinuityCheck(ctx context.Context, arg CreateContinuityCheckParams) error {
	_, err := q.db.ExecContext(ctx, createContinuityCheck, arg.PreviousCaptureID, arg.CurrentCaptureID, arg.Now)
	return err
}

const deleteContinuityCheck = `-- name: DeleteContinuityCheck :exec
DELETE FROM feed_continuity_checks WHERE previous_capture_id = ? AND current_capture_id = ?
`

type DeleteContinuityCheckParams struct {
	PreviousCaptureID int64
	CurrentCaptureID  int64
}

func (q *Queries) DeleteContinuityCheck(ctx context.Context, arg DeleteContinuityCheckParams) error {
	_, err := q.db.ExecContext(ctx, deleteContinuityCheck, arg.PreviousCaptureID, arg.CurrentCaptureID)
	return err
}

const hasFeedSighting = `-- name: HasFeedSighting :one
SELECT EXISTS(SELECT 1 FROM feed_gallery_refs WHERE gallery_id = ? AND raw_feed_id != ?)
`

type HasFeedSightingParams struct {
	GalleryID int64
	RawFeedID int64
}

func (q *Queries) HasFeedSighting(ctx context.Context, arg HasFeedSightingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasFeedSighting, arg.GalleryID, arg.RawFeedID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const latestCaptureTime = `-- name: LatestCaptureTime :one
SELECT captured_at FROM raw_feeds ORDER BY captured_at DESC, id DESC LIMIT 1
`

func (q *Queries) LatestCaptureTime(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestCaptureTime)
	var captured_at int64
	err := row.Scan(&captured_at)
	return captured_at, err
}

const markProcessed = `-- name: MarkProcessed :exec
UPDATE raw_feeds SET processed_at = ?1, last_attempt_at = ?1, last_error = NULL WHERE id = ?2
`

type MarkProcessedParams struct {
	Now sql.NullInt64
	ID  int64
}

func (q *Queries) MarkProcessed(ctx context.Context, arg MarkProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markProcessed, arg.Now, arg.ID)
	return err
}

const nextCapture = `-- name: NextCapture :one
SELECT id FROM raw_feeds
WHERE (captured_at, id) > (?1, ?2)
ORDER BY captured_at, id LIMIT 1
`

type NextCaptureParams struct {
	CapturedAt int64
	ID         int64
}

func (q *Queries) NextCapture(ctx context.Context, arg NextCaptureParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextCapture, arg.CapturedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const pendingCaptures = `-- name: PendingCaptures :many
SELECT id FROM raw_feeds WHERE processed_at IS NULL ORDER BY captured_at, id
`

func (q *Queries) PendingCaptures(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, pendingCaptures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const previousCapture = `-- name: PreviousCapture :one
SELECT id FROM raw_feeds
WHERE (captured_at, id) < (?1, ?2)
ORDER BY captured_at DESC, id DESC LIMIT 1
`

type PreviousCaptureParams struct {
	CapturedAt int64
	ID         int64
}

func (q *Queries) PreviousCapture(ctx context.Context, arg PreviousCaptureParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, previousCapture, arg.CapturedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const recordFailure = `-- name: RecordFailure :exec
UPDATE raw_feeds SET last_attempt_at = ?, last_error = ? WHERE id = ? AND processed_at IS NULL
`

type RecordFailureParams struct {
	LastAttemptAt sql.NullInt64
	LastError     sql.NullString
	ID            int64
}

func (q *Queries) RecordFailure(ctx context.Context, arg RecordFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordFailure, arg.LastAttemptAt, arg.LastError, arg.ID)
	return err
}

const saveCapture = `-- name: SaveCapture :one
INSERT INTO raw_feeds (captured_at, feed_url, body) VALUES (?, ?, ?) RETURNING id
`

type SaveCaptureParams struct {
	CapturedAt int64
	FeedUrl    string
	Body       []byte
}

func (q *Queries) SaveCapture(ctx context.Context, arg SaveCaptureParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, saveCapture, arg.CapturedAt, arg.FeedUrl, arg.Body)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const saveFeedGalleryRef = `-- name: SaveFeedGalleryRef :exec
INSERT INTO feed_gallery_refs (raw_feed_id, gallery_id) VALUES (?, ?)
ON CONFLICT (raw_feed_id, gallery_id) DO NOTHING
`

type SaveFeedGalleryRefParams struct {
	RawFeedID int64
	GalleryID int64
}

func (q *Queries) SaveFeedGalleryRef(ctx context.Context, arg SaveFeedGalleryRefParams) error {
	_, err := q.db.ExecContext(ctx, saveFeedGalleryRef, arg.RawFeedID, arg.GalleryID)
	return err
}

const saveGalleryRef = `-- name: SaveGalleryRef :exec
INSERT INTO gallery_refs (gallery_id, token) VALUES (?, ?) ON CONFLICT (gallery_id) DO NOTHING
`

type SaveGalleryRefParams struct {
	GalleryID int64
	Token     string
}

func (q *Queries) SaveGalleryRef(ctx context.Context, arg SaveGalleryRefParams) error {
	_, err := q.db.ExecContext(ctx, saveGalleryRef, arg.GalleryID, arg.Token)
	return err
}
