// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
)

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = ?
`

func (q *Queries) DeleteSource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const listSources = `-- name: ListSources :many
SELECT s.id, s.library_id, s.path, s.kind,
       l.name AS library_name, l.path AS library_path,
       EXISTS (
           SELECT 1 FROM source_files f
           JOIN gallery_pages p ON p.source_file_id = f.id
           JOIN galleries g ON g.id = p.gallery_id
           WHERE f.source_id = s.id AND (g.source_id IS NULL OR g.source_id != s.id)
       ) AS protected
FROM sources s JOIN libraries l ON l.id = s.library_id
ORDER BY l.name, s.path, s.id
`

type ListSourcesRow struct {
	ID          int64
	LibraryID   int64
	Path        string
	Kind        string
	LibraryName string
	LibraryPath string
	Protected   int64
}

func (q *Queries) ListSources(ctx context.Context) ([]ListSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourcesRow{}
	for rows.Next() {
		var i ListSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Path,
			&i.Kind,
			&i.LibraryName,
			&i.LibraryPath,
			&i.Protected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
