#!/usr/bin/env python3
"""Generate a disposable library for gallery, tag, and reader UI checks.

Requires Python 3 and ImageMagick 7 (`magick`). Run from any directory:
    ./scripts/generate-test-galleries.py
    ./scripts/generate-test-galleries.py --count 40 --pages 8

Register the printed library root in Tana and scan it. Rerunning replaces the
generated library. Use a fresh Tana catalog to reimport changed metadata or pages;
scans only import source paths that are not already registered.
"""

import argparse
from pathlib import Path
import shutil
import subprocess
import tempfile
import zipfile


OUTPUT = Path(__file__).resolve().parents[1] / "test-galleries"
MARKER = ".tana-generated-fixtures"
CASES = [
    ("Grouped tags", [
        "language:japanese", "artist:zeta studio", "all ages",
        "artist:alpha studio", "parody:paper moon", "language:english",
        "character:aki", "group:demo circle",
    ]),
    ("No tags", []),
    ("Many tags", [
        f"{namespace}:sample tag {number:02d}"
        for namespace in ("theme", "character", "artist")
        for number in range(20, 0, -1)
    ]),
    ("Long values", [
        "other:" + "longtag" * 20,
        "artist:a fictional studio with a deliberately long descriptive name",
        "theme:a long tag value with spaces that can wrap onto several lines",
    ]),
    ("Custom namespaces", [
        "mood:quiet", "setting:moon station", "custom:alpha studio",
        "artist:alpha studio", "all ages", "multi-work series",
    ]),
    ("Single tag", ["language:english"]),
]
COLORS = ["#405c70", "#73516b", "#4c6a51", "#855c3c", "#615a89", "#396c70"]


def positive_int(value):
    number = int(value)
    if number < 1:
        raise argparse.ArgumentTypeError("must be at least 1")
    return number


def write_metadata(directory, title, tags):
    lines = [
        f"Title: {title}",
        "Upload Time: 2026-01-01 12:00",
        "Uploaded By: tana-fixtures",
        "Downloaded: 2026-01-02 12:00",
    ]
    # An omitted Tags header represents no tags; an empty header is malformed.
    if tags:
        lines.append("Tags: " + ", ".join(tags))
    lines.extend([
        "", "Uploader's Comments:", "",
        "Synthetic gallery for local UI testing. All names and metadata are fake.",
        "", "Generated by Tana's test gallery script.", "",
    ])
    (directory / "galleryinfo.txt").write_text("\n".join(lines), encoding="utf-8")


def generate(library, count, pages, font):
    for index in range(count):
        label, tags = CASES[index % len(CASES)]
        title = f"Test {index + 1:03d} - {label}"
        name = f"{index + 1:03d}-{label.lower().replace(' ', '-')}"
        directory = library / name
        directory.mkdir()
        write_metadata(directory, title, tags)
        for page in range(1, pages + 1):
            wide = page % 3 == 0
            geometry = "1600x1000" if wide else "800x1200"
            caption = f"{title}\n\nPage {page:03d} / {pages:03d}\n\n{'Landscape spread' if wide else 'Portrait page'}"
            subprocess.run([
                "magick", "-size", geometry,
                "xc:" + COLORS[index % len(COLORS)],
                "-font", font, "-fill", "white", "-gravity", "center",
                "-pointsize", "36", "-annotate", "0", caption,
                "-strip", str(directory / f"{page:03d}.png"),
            ], check=True)
        if index % 2:
            archive_path = library / f"{name}.cbz"
            with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED) as archive:
                for file in sorted(directory.iterdir()):
                    archive.write(file, arcname=f"{name}/{file.name}")
            shutil.rmtree(directory)
            print(archive_path.name, flush=True)
        else:
            print(directory.name + "/", flush=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--count", type=positive_int, default=6, help="number of galleries (default: 6; cases repeat)")
    parser.add_argument("--pages", type=positive_int, default=5, help="pages per gallery (default: 5)")
    parser.add_argument("--font", default="DejaVu-Sans", help="ImageMagick font name (default: DejaVu-Sans)")
    args = parser.parse_args()
    if not shutil.which("magick"):
        parser.error("ImageMagick 7 is required; 'magick' was not found on PATH")
    if OUTPUT.is_symlink() or (OUTPUT.exists() and not (OUTPUT / MARKER).is_file()):
        parser.error(f"refusing to replace {OUTPUT}: not a generated fixture library")
    try:
        # Keep the previous fixtures intact if rendering fails. Stage alongside
        # the destination so moving the finished library stays on one filesystem.
        with tempfile.TemporaryDirectory(prefix=".tana-fixtures-", dir=OUTPUT.parent) as temporary:
            library = Path(temporary) / "library"
            library.mkdir()
            generate(library, args.count, args.pages, args.font)
            (library / MARKER).write_text("Generated by scripts/generate-test-galleries.py\n", encoding="utf-8")
            if OUTPUT.exists():
                shutil.rmtree(OUTPUT)
            library.rename(OUTPUT)
    except (OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"Generation failed: {error}\n")
    print(f"\nLibrary root: {OUTPUT}\nGenerated {args.count} galleries, {args.pages} pages each.")


if __name__ == "__main__":
    main()
