// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
)

const deleteFavorites = `-- name: DeleteFavorites :exec
DELETE FROM favorites WHERE category_id = ?
`

func (q *Queries) DeleteFavorites(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFavorites, categoryID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id FROM favorite_categories WHERE host = ? AND account_key = ? AND category = ?
`

type GetCategoryParams struct {
	Host       string
	AccountKey string
	Category   int64
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCategory, arg.Host, arg.AccountKey, arg.Category)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const knownFavorites = `-- name: KnownFavorites :many
SELECT gallery_id, added_at FROM favorites WHERE category_id = ?
`

type KnownFavoritesRow struct {
	GalleryID int64
	AddedAt   int64
}

func (q *Queries) KnownFavorites(ctx context.Context, categoryID int64) ([]KnownFavoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, knownFavorites, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnownFavoritesRow{}
	for rows.Next() {
		var i KnownFavoritesRow
		if err := rows.Scan(&i.GalleryID, &i.AddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCategory = `-- name: SaveCategory :one
INSERT INTO favorite_categories (host, account_key, category, name, synced_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (host, account_key, category) DO UPDATE SET name = excluded.name, synced_at = excluded.synced_at
RETURNING id
`

type SaveCategoryParams struct {
	Host       string
	AccountKey string
	Category   int64
	Name       string
	SyncedAt   int64
}

func (q *Queries) SaveCategory(ctx context.Context, arg SaveCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, saveCategory,
		arg.Host,
		arg.AccountKey,
		arg.Category,
		arg.Name,
		arg.SyncedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const saveFavorite = `-- name: SaveFavorite :exec
INSERT INTO favorites (category_id, gallery_id, token, added_at) VALUES (?, ?, ?, ?)
ON CONFLICT (category_id, gallery_id) DO UPDATE SET token = excluded.token, added_at = excluded.added_at
`

type SaveFavoriteParams struct {
	CategoryID int64
	GalleryID  int64
	Token      string
	AddedAt    int64
}

func (q *Queries) SaveFavorite(ctx context.Context, arg SaveFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, saveFavorite,
		arg.CategoryID,
		arg.GalleryID,
		arg.Token,
		arg.AddedAt,
	)
	return err
}

const saveGalleryRef = `-- name: SaveGalleryRef :exec
INSERT INTO gallery_refs (gallery_id, token) VALUES (?, ?) ON CONFLICT (gallery_id) DO NOTHING
`

type SaveGalleryRefParams struct {
	GalleryID int64
	Token     string
}

func (q *Queries) SaveGalleryRef(ctx context.Context, arg SaveGalleryRefParams) error {
	_, err := q.db.ExecContext(ctx, saveGalleryRef, arg.GalleryID, arg.Token)
	return err
}
