// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const baselineCategories = `-- name: BaselineCategories :many
SELECT category FROM favorite_download_baseline ORDER BY category
`

func (q *Queries) BaselineCategories(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, baselineCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var category int64
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryStatistics = `-- name: CategoryStatistics :many
SELECT c.category, c.name, c.synced_at, count(f.gallery_id) AS favorites
FROM favorite_categories c LEFT JOIN favorites f ON f.category_id = c.id
WHERE c.host = ? AND c.account_key = ?
GROUP BY c.id ORDER BY c.category
`

type CategoryStatisticsParams struct {
	Host       string
	AccountKey string
}

type CategoryStatisticsRow struct {
	Category  int64
	Name      string
	SyncedAt  int64
	Favorites int64
}

func (q *Queries) CategoryStatistics(ctx context.Context, arg CategoryStatisticsParams) ([]CategoryStatisticsRow, error) {
	rows, err := q.db.QueryContext(ctx, categoryStatistics, arg.Host, arg.AccountKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryStatisticsRow{}
	for rows.Next() {
		var i CategoryStatisticsRow
		if err := rows.Scan(
			&i.Category,
			&i.Name,
			&i.SyncedAt,
			&i.Favorites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearDownloadCategories = `-- name: ClearDownloadCategories :exec
DELETE FROM favorite_download_categories
`

func (q *Queries) ClearDownloadCategories(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDownloadCategories)
	return err
}

const clearSeenFavorites = `-- name: ClearSeenFavorites :exec
DELETE FROM favorite_sync_seen WHERE category_id = ?
`

func (q *Queries) ClearSeenFavorites(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, clearSeenFavorites, categoryID)
	return err
}

const clearVisitedPages = `-- name: ClearVisitedPages :exec
DELETE FROM favorite_sync_pages WHERE category_id = ?
`

func (q *Queries) ClearVisitedPages(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, clearVisitedPages, categoryID)
	return err
}

const commitFavorites = `-- name: CommitFavorites :exec
UPDATE favorites SET committed_added_at = added_at WHERE favorites.category_id = ?1
    AND gallery_id IN (SELECT gallery_id FROM favorite_sync_seen WHERE favorite_sync_seen.category_id = ?1)
`

func (q *Queries) CommitFavorites(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, commitFavorites, categoryID)
	return err
}

const completeBaselineCategory = `-- name: CompleteBaselineCategory :exec
INSERT INTO favorite_download_baseline (category) VALUES (?) ON CONFLICT DO NOTHING
`

func (q *Queries) CompleteBaselineCategory(ctx context.Context, category int64) error {
	_, err := q.db.ExecContext(ctx, completeBaselineCategory, category)
	return err
}

const completeCategory = `-- name: CompleteCategory :exec
UPDATE favorite_categories SET synced_at = ? WHERE id = ?
`

type CompleteCategoryParams struct {
	SyncedAt int64
	ID       int64
}

func (q *Queries) CompleteCategory(ctx context.Context, arg CompleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, completeCategory, arg.SyncedAt, arg.ID)
	return err
}

const downloadBaselineState = `-- name: DownloadBaselineState :one
SELECT baseline_state FROM favorite_download_settings WHERE id = 1
`

func (q *Queries) DownloadBaselineState(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, downloadBaselineState)
	var baseline_state string
	err := row.Scan(&baseline_state)
	return baseline_state, err
}

const downloadCategories = `-- name: DownloadCategories :many
SELECT category FROM favorite_download_categories ORDER BY category
`

func (q *Queries) DownloadCategories(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, downloadCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var category int64
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enableDownloadCategory = `-- name: EnableDownloadCategory :exec
INSERT INTO favorite_download_categories (category) VALUES (?) ON CONFLICT DO NOTHING
`

func (q *Queries) EnableDownloadCategory(ctx context.Context, category int64) error {
	_, err := q.db.ExecContext(ctx, enableDownloadCategory, category)
	return err
}

const failSync = `-- name: FailSync :exec
UPDATE favorite_syncs SET state = ?, last_error = ?, last_error_at = ?, retry_at = ?, finished_at = ?, failures = failures + 1 WHERE category_id = ?
`

type FailSyncParams struct {
	State       string
	LastError   string
	LastErrorAt int64
	RetryAt     int64
	FinishedAt  int64
	CategoryID  int64
}

func (q *Queries) FailSync(ctx context.Context, arg FailSyncParams) error {
	_, err := q.db.ExecContext(ctx, failSync,
		arg.State,
		arg.LastError,
		arg.LastErrorAt,
		arg.RetryAt,
		arg.FinishedAt,
		arg.CategoryID,
	)
	return err
}

const finishDownloadBaseline = `-- name: FinishDownloadBaseline :exec
UPDATE favorite_download_settings SET baseline_state = 'ready'
WHERE id = 1 AND baseline_state = 'collecting' AND (SELECT count(*) FROM favorite_download_baseline) = 10
`

func (q *Queries) FinishDownloadBaseline(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, finishDownloadBaseline)
	return err
}

const finishSync = `-- name: FinishSync :exec
UPDATE favorite_syncs SET state = 'success', finished_at = ?, retry_at = 0 WHERE category_id = ?
`

type FinishSyncParams struct {
	FinishedAt int64
	CategoryID int64
}

func (q *Queries) FinishSync(ctx context.Context, arg FinishSyncParams) error {
	_, err := q.db.ExecContext(ctx, finishSync, arg.FinishedAt, arg.CategoryID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, synced_at FROM favorite_categories WHERE host = ? AND account_key = ? AND category = ?
`

type GetCategoryParams struct {
	Host       string
	AccountKey string
	Category   int64
}

type GetCategoryRow struct {
	ID       int64
	SyncedAt int64
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (GetCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getCategory, arg.Host, arg.AccountKey, arg.Category)
	var i GetCategoryRow
	err := row.Scan(&i.ID, &i.SyncedAt)
	return i, err
}

const getSync = `-- name: GetSync :one
SELECT category_id, state, "full", followup_full, queued_at, next_url, pages_saved, entries_saved, last_saved_at, last_added_at, restarted, started_at, finished_at, last_error, last_error_at, retry_at, failures FROM favorite_syncs WHERE category_id = ?
`

func (q *Queries) GetSync(ctx context.Context, categoryID int64) (FavoriteSync, error) {
	row := q.db.QueryRowContext(ctx, getSync, categoryID)
	var i FavoriteSync
	err := row.Scan(
		&i.CategoryID,
		&i.State,
		&i.Full,
		&i.FollowupFull,
		&i.QueuedAt,
		&i.NextUrl,
		&i.PagesSaved,
		&i.EntriesSaved,
		&i.LastSavedAt,
		&i.LastAddedAt,
		&i.Restarted,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LastError,
		&i.LastErrorAt,
		&i.RetryAt,
		&i.Failures,
	)
	return i, err
}

const knownFavorites = `-- name: KnownFavorites :many
SELECT gallery_id, committed_added_at FROM favorites WHERE category_id = ? AND committed_added_at IS NOT NULL
`

type KnownFavoritesRow struct {
	GalleryID        int64
	CommittedAddedAt sql.NullInt64
}

func (q *Queries) KnownFavorites(ctx context.Context, categoryID int64) ([]KnownFavoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, knownFavorites, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnownFavoritesRow{}
	for rows.Next() {
		var i KnownFavoritesRow
		if err := rows.Scan(&i.GalleryID, &i.CommittedAddedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncs = `-- name: ListSyncs :many
SELECT s.category_id, s.state, s."full", s.followup_full, s.queued_at, s.next_url, s.pages_saved, s.entries_saved, s.last_saved_at, s.last_added_at, s.restarted, s.started_at, s.finished_at, s.last_error, s.last_error_at, s.retry_at, s.failures, c.category FROM favorite_syncs s JOIN favorite_categories c ON c.id = s.category_id
WHERE c.host = ? AND c.account_key = ?
`

type ListSyncsParams struct {
	Host       string
	AccountKey string
}

type ListSyncsRow struct {
	FavoriteSync FavoriteSync
	Category     int64
}

func (q *Queries) ListSyncs(ctx context.Context, arg ListSyncsParams) ([]ListSyncsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSyncs, arg.Host, arg.AccountKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncsRow{}
	for rows.Next() {
		var i ListSyncsRow
		if err := rows.Scan(
			&i.FavoriteSync.CategoryID,
			&i.FavoriteSync.State,
			&i.FavoriteSync.Full,
			&i.FavoriteSync.FollowupFull,
			&i.FavoriteSync.QueuedAt,
			&i.FavoriteSync.NextUrl,
			&i.FavoriteSync.PagesSaved,
			&i.FavoriteSync.EntriesSaved,
			&i.FavoriteSync.LastSavedAt,
			&i.FavoriteSync.LastAddedAt,
			&i.FavoriteSync.Restarted,
			&i.FavoriteSync.StartedAt,
			&i.FavoriteSync.FinishedAt,
			&i.FavoriteSync.LastError,
			&i.FavoriteSync.LastErrorAt,
			&i.FavoriteSync.RetryAt,
			&i.FavoriteSync.Failures,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newSync = `-- name: NewSync :exec
INSERT INTO favorite_syncs (category_id, state, full, queued_at) VALUES (?, 'queued', ?, ?)
ON CONFLICT (category_id) DO UPDATE SET state = 'queued', full = excluded.full,
    followup_full = 0, queued_at = excluded.queued_at, next_url = '', pages_saved = 0,
    entries_saved = 0, last_saved_at = 0, last_added_at = 0, restarted = 0,
    started_at = 0, finished_at = 0, last_error = '', last_error_at = 0, retry_at = 0, failures = 0
`

type NewSyncParams struct {
	CategoryID int64
	Full       int64
	QueuedAt   int64
}

func (q *Queries) NewSync(ctx context.Context, arg NewSyncParams) error {
	_, err := q.db.ExecContext(ctx, newSync, arg.CategoryID, arg.Full, arg.QueuedAt)
	return err
}

const nextSync = `-- name: NextSync :one
SELECT s.category_id, s.state, s."full", s.followup_full, s.queued_at, s.next_url, s.pages_saved, s.entries_saved, s.last_saved_at, s.last_added_at, s.restarted, s.started_at, s.finished_at, s.last_error, s.last_error_at, s.retry_at, s.failures, c.category FROM favorite_syncs s JOIN favorite_categories c ON c.id = s.category_id
WHERE c.host = ? AND c.account_key = ? AND (s.state IN ('queued', 'running') OR s.followup_full = 1)
ORDER BY s.state = 'running' DESC, s.queued_at, c.category LIMIT 1
`

type NextSyncParams struct {
	Host       string
	AccountKey string
}

type NextSyncRow struct {
	FavoriteSync FavoriteSync
	Category     int64
}

func (q *Queries) NextSync(ctx context.Context, arg NextSyncParams) (NextSyncRow, error) {
	row := q.db.QueryRowContext(ctx, nextSync, arg.Host, arg.AccountKey)
	var i NextSyncRow
	err := row.Scan(
		&i.FavoriteSync.CategoryID,
		&i.FavoriteSync.State,
		&i.FavoriteSync.Full,
		&i.FavoriteSync.FollowupFull,
		&i.FavoriteSync.QueuedAt,
		&i.FavoriteSync.NextUrl,
		&i.FavoriteSync.PagesSaved,
		&i.FavoriteSync.EntriesSaved,
		&i.FavoriteSync.LastSavedAt,
		&i.FavoriteSync.LastAddedAt,
		&i.FavoriteSync.Restarted,
		&i.FavoriteSync.StartedAt,
		&i.FavoriteSync.FinishedAt,
		&i.FavoriteSync.LastError,
		&i.FavoriteSync.LastErrorAt,
		&i.FavoriteSync.RetryAt,
		&i.FavoriteSync.Failures,
		&i.Category,
	)
	return i, err
}

const observeFavorite = `-- name: ObserveFavorite :execrows
INSERT INTO favorite_observations (gallery_id) VALUES (?) ON CONFLICT DO NOTHING
`

func (q *Queries) ObserveFavorite(ctx context.Context, galleryID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, observeFavorite, galleryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const queueFullSync = `-- name: QueueFullSync :exec
UPDATE favorite_syncs SET followup_full = 1 WHERE category_id = ?
`

func (q *Queries) QueueFullSync(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, queueFullSync, categoryID)
	return err
}

const reconcileFavorites = `-- name: ReconcileFavorites :exec
DELETE FROM favorites WHERE favorites.category_id = ?1 AND gallery_id NOT IN
    (SELECT gallery_id FROM favorite_sync_seen WHERE favorite_sync_seen.category_id = ?1)
`

func (q *Queries) ReconcileFavorites(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, reconcileFavorites, categoryID)
	return err
}

const renameCategory = `-- name: RenameCategory :exec
UPDATE favorite_categories SET name = ? WHERE id = ?
`

type RenameCategoryParams struct {
	Name string
	ID   int64
}

func (q *Queries) RenameCategory(ctx context.Context, arg RenameCategoryParams) error {
	_, err := q.db.ExecContext(ctx, renameCategory, arg.Name, arg.ID)
	return err
}

const restartTraversal = `-- name: RestartTraversal :exec
UPDATE favorite_syncs SET next_url = '', pages_saved = 0, entries_saved = 0,
    last_added_at = 0, restarted = 1 WHERE category_id = ?
`

func (q *Queries) RestartTraversal(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, restartTraversal, categoryID)
	return err
}

const resumeFailedBaselineSyncs = `-- name: ResumeFailedBaselineSyncs :exec
UPDATE favorite_syncs SET state = 'queued', finished_at = 0, retry_at = 0, failures = 0, restarted = 0
WHERE state = 'failed' AND (SELECT baseline_state FROM favorite_download_settings WHERE id = 1) = 'collecting'
    AND category_id IN (SELECT id FROM favorite_categories WHERE host = ? AND account_key = ?)
`

type ResumeFailedBaselineSyncsParams struct {
	Host       string
	AccountKey string
}

func (q *Queries) ResumeFailedBaselineSyncs(ctx context.Context, arg ResumeFailedBaselineSyncsParams) error {
	_, err := q.db.ExecContext(ctx, resumeFailedBaselineSyncs, arg.Host, arg.AccountKey)
	return err
}

const resumeSync = `-- name: ResumeSync :exec
UPDATE favorite_syncs SET state = 'queued', finished_at = 0, retry_at = 0, failures = 0, restarted = 0 WHERE category_id = ?
`

func (q *Queries) ResumeSync(ctx context.Context, categoryID int64) error {
	_, err := q.db.ExecContext(ctx, resumeSync, categoryID)
	return err
}

const saveCategory = `-- name: SaveCategory :one
INSERT INTO favorite_categories (host, account_key, category, name, synced_at) VALUES (?, ?, ?, '', 0)
ON CONFLICT (host, account_key, category) DO UPDATE SET host = excluded.host
RETURNING id
`

type SaveCategoryParams struct {
	Host       string
	AccountKey string
	Category   int64
}

func (q *Queries) SaveCategory(ctx context.Context, arg SaveCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, saveCategory, arg.Host, arg.AccountKey, arg.Category)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const saveFavorite = `-- name: SaveFavorite :exec
INSERT INTO favorites (category_id, gallery_id, token, added_at) VALUES (?, ?, ?, ?)
ON CONFLICT (category_id, gallery_id) DO UPDATE SET token = excluded.token, added_at = excluded.added_at
`

type SaveFavoriteParams struct {
	CategoryID int64
	GalleryID  int64
	Token      string
	AddedAt    int64
}

func (q *Queries) SaveFavorite(ctx context.Context, arg SaveFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, saveFavorite,
		arg.CategoryID,
		arg.GalleryID,
		arg.Token,
		arg.AddedAt,
	)
	return err
}

const saveGalleryRef = `-- name: SaveGalleryRef :exec
INSERT INTO gallery_refs (gallery_id, token) VALUES (?, ?)
ON CONFLICT (gallery_id) DO UPDATE SET metadata_priority = 0
`

type SaveGalleryRefParams struct {
	GalleryID int64
	Token     string
}

func (q *Queries) SaveGalleryRef(ctx context.Context, arg SaveGalleryRefParams) error {
	_, err := q.db.ExecContext(ctx, saveGalleryRef, arg.GalleryID, arg.Token)
	return err
}

const saveProgress = `-- name: SaveProgress :exec
UPDATE favorite_syncs SET next_url = ?1, pages_saved = pages_saved + 1,
    entries_saved = (SELECT count(*) FROM favorite_sync_seen WHERE favorite_sync_seen.category_id = ?2),
    last_saved_at = ?3, last_added_at = ?4, retry_at = 0, failures = 0 WHERE favorite_syncs.category_id = ?2
`

type SaveProgressParams struct {
	NextUrl     string
	CategoryID  int64
	LastSavedAt int64
	LastAddedAt int64
}

func (q *Queries) SaveProgress(ctx context.Context, arg SaveProgressParams) error {
	_, err := q.db.ExecContext(ctx, saveProgress,
		arg.NextUrl,
		arg.CategoryID,
		arg.LastSavedAt,
		arg.LastAddedAt,
	)
	return err
}

const saveSeenFavorite = `-- name: SaveSeenFavorite :exec
INSERT INTO favorite_sync_seen (category_id, gallery_id) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type SaveSeenFavoriteParams struct {
	CategoryID int64
	GalleryID  int64
}

func (q *Queries) SaveSeenFavorite(ctx context.Context, arg SaveSeenFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, saveSeenFavorite, arg.CategoryID, arg.GalleryID)
	return err
}

const saveVisitedPage = `-- name: SaveVisitedPage :exec
INSERT INTO favorite_sync_pages (category_id, url) VALUES (?, ?)
`

type SaveVisitedPageParams struct {
	CategoryID int64
	Url        string
}

func (q *Queries) SaveVisitedPage(ctx context.Context, arg SaveVisitedPageParams) error {
	_, err := q.db.ExecContext(ctx, saveVisitedPage, arg.CategoryID, arg.Url)
	return err
}

const seedFavoriteObservations = `-- name: SeedFavoriteObservations :exec
INSERT INTO favorite_observations (gallery_id) SELECT DISTINCT gallery_id FROM favorites WHERE true ON CONFLICT DO NOTHING
`

func (q *Queries) SeedFavoriteObservations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedFavoriteObservations)
	return err
}

const seenFavorites = `-- name: SeenFavorites :many
SELECT gallery_id FROM favorite_sync_seen WHERE category_id = ?
`

func (q *Queries) SeenFavorites(ctx context.Context, categoryID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, seenFavorites, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var gallery_id int64
		if err := rows.Scan(&gallery_id); err != nil {
			return nil, err
		}
		items = append(items, gallery_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startDownloadBaseline = `-- name: StartDownloadBaseline :exec
UPDATE favorite_download_settings SET baseline_state = 'collecting' WHERE id = 1
`

func (q *Queries) StartDownloadBaseline(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, startDownloadBaseline)
	return err
}

const startSync = `-- name: StartSync :exec
UPDATE favorite_syncs SET state = 'running', started_at = CASE WHEN started_at = 0 THEN ? ELSE started_at END WHERE category_id = ?
`

type StartSyncParams struct {
	StartedAt  int64
	CategoryID int64
}

func (q *Queries) StartSync(ctx context.Context, arg StartSyncParams) error {
	_, err := q.db.ExecContext(ctx, startSync, arg.StartedAt, arg.CategoryID)
	return err
}

const visitedPages = `-- name: VisitedPages :many
SELECT url FROM favorite_sync_pages WHERE category_id = ?
`

func (q *Queries) VisitedPages(ctx context.Context, categoryID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, visitedPages, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
