// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
)

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = ?
`

func (q *Queries) DeleteSource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const listAffectedGalleries = `-- name: ListAffectedGalleries :many
SELECT g.id AS id, g.title, 1 AS deleted,
       (SELECT count(*) FROM gallery_pages p WHERE p.gallery_id = g.id) AS pages_removed
FROM sources s JOIN galleries g ON g.source_id = s.id
WHERE s.id = ?1
UNION ALL
SELECT g.id AS id, g.title, 0 AS deleted, count(*) AS pages_removed
FROM gallery_pages p
JOIN source_files f ON f.id = p.source_file_id
JOIN galleries g ON g.id = p.gallery_id
WHERE f.source_id = ?1
  AND (g.source_id IS NULL OR g.source_id != ?1)
GROUP BY g.id
ORDER BY id
`

type ListAffectedGalleriesRow struct {
	ID           int64
	Title        string
	Deleted      int64
	PagesRemoved int64
}

func (q *Queries) ListAffectedGalleries(ctx context.Context, sourceID int64) ([]ListAffectedGalleriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAffectedGalleries, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAffectedGalleriesRow{}
	for rows.Next() {
		var i ListAffectedGalleriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Deleted,
			&i.PagesRemoved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT s.id, s.library_id, s.path, s.kind,
       l.name AS library_name, l.path AS library_path
FROM sources s JOIN libraries l ON l.id = s.library_id
WHERE s.library_id = ?1 OR ?1 = 0
ORDER BY l.id, s.path, s.id
`

type ListSourcesRow struct {
	ID          int64
	LibraryID   int64
	Path        string
	Kind        string
	LibraryName string
	LibraryPath string
}

func (q *Queries) ListSources(ctx context.Context, libraryID int64) ([]ListSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSources, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourcesRow{}
	for rows.Next() {
		var i ListSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Path,
			&i.Kind,
			&i.LibraryName,
			&i.LibraryPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
