// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

type Source struct {
	ID        string
	LibraryID string
	Path      string
	Kind      string
}

type SourceFile struct {
	ID       string
	SourceID string
	Path     string
}
