// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

type Source struct {
	ID        int64
	LibraryID int64
	Path      string
	Kind      string
}

type SourceFile struct {
	ID       int64
	SourceID int64
	Path     string
}
