// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (id, library_id, path, kind) VALUES (?, ?, ?, ?) RETURNING id, library_id, path, kind
`

type CreateSourceParams struct {
	ID        string
	LibraryID string
	Path      string
	Kind      string
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (Source, error) {
	row := q.db.QueryRowContext(ctx, createSource,
		arg.ID,
		arg.LibraryID,
		arg.Path,
		arg.Kind,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Path,
		&i.Kind,
	)
	return i, err
}

const createSourceFile = `-- name: CreateSourceFile :exec
INSERT INTO source_files (id, source_id, path) VALUES (?, ?, ?)
`

type CreateSourceFileParams struct {
	ID       string
	SourceID string
	Path     string
}

func (q *Queries) CreateSourceFile(ctx context.Context, arg CreateSourceFileParams) error {
	_, err := q.db.ExecContext(ctx, createSourceFile, arg.ID, arg.SourceID, arg.Path)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = ?
`

func (q *Queries) DeleteSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const getSource = `-- name: GetSource :one
SELECT id, library_id, path, kind FROM sources WHERE id = ?
`

func (q *Queries) GetSource(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Path,
		&i.Kind,
	)
	return i, err
}

const listSourceFiles = `-- name: ListSourceFiles :many
SELECT id, source_id, path FROM source_files WHERE source_id = ? ORDER BY path, id
`

func (q *Queries) ListSourceFiles(ctx context.Context, sourceID string) ([]SourceFile, error) {
	rows, err := q.db.QueryContext(ctx, listSourceFiles, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceFile{}
	for rows.Next() {
		var i SourceFile
		if err := rows.Scan(&i.ID, &i.SourceID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, library_id, path, kind FROM sources WHERE library_id = ? ORDER BY path, id
`

func (q *Queries) ListSources(ctx context.Context, libraryID string) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Path,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
