// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

type Namespace struct {
	ID   string
	Name string
}

type Tag struct {
	ID          string
	NamespaceID string
	Value       string
}
