// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

type Namespace struct {
	ID   int64
	Name string
}

type Tag struct {
	ID          int64
	NamespaceID int64
	Value       string
}
