// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
)

const assignGalleryTag = `-- name: AssignGalleryTag :exec
INSERT INTO gallery_tags (gallery_id, tag_id) VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AssignGalleryTagParams struct {
	GalleryID int64
	TagID     int64
}

func (q *Queries) AssignGalleryTag(ctx context.Context, arg AssignGalleryTagParams) error {
	_, err := q.db.ExecContext(ctx, assignGalleryTag, arg.GalleryID, arg.TagID)
	return err
}

const deleteGalleryTags = `-- name: DeleteGalleryTags :exec
DELETE FROM gallery_tags WHERE gallery_id = ?
`

func (q *Queries) DeleteGalleryTags(ctx context.Context, galleryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteGalleryTags, galleryID)
	return err
}

const ensureNamespace = `-- name: EnsureNamespace :one
INSERT INTO namespaces (name) VALUES (?)
ON CONFLICT (name) DO UPDATE SET name = excluded.name RETURNING id, name
`

func (q *Queries) EnsureNamespace(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, ensureNamespace, name)
	var i Namespace
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const ensureTag = `-- name: EnsureTag :one
INSERT INTO tags (namespace_id, value) VALUES (?, ?)
ON CONFLICT (namespace_id, value) DO UPDATE SET value = excluded.value RETURNING id, namespace_id, value
`

type EnsureTagParams struct {
	NamespaceID int64
	Value       string
}

func (q *Queries) EnsureTag(ctx context.Context, arg EnsureTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, ensureTag, arg.NamespaceID, arg.Value)
	var i Tag
	err := row.Scan(&i.ID, &i.NamespaceID, &i.Value)
	return i, err
}

const listGalleryTags = `-- name: ListGalleryTags :many
SELECT t.id, t.value, n.id AS namespace_id, n.name AS namespace_name
FROM gallery_tags g JOIN tags t ON t.id = g.tag_id
JOIN namespaces n ON n.id = t.namespace_id
WHERE g.gallery_id = ? ORDER BY n.name, t.value
`

type ListGalleryTagsRow struct {
	ID            int64
	Value         string
	NamespaceID   int64
	NamespaceName string
}

func (q *Queries) ListGalleryTags(ctx context.Context, galleryID int64) ([]ListGalleryTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGalleryTags, galleryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGalleryTagsRow{}
	for rows.Next() {
		var i ListGalleryTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.NamespaceID,
			&i.NamespaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
