// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
)

const complete = `-- name: Complete :exec
DELETE FROM panda_enrichments WHERE gallery_id = ?
`

func (q *Queries) Complete(ctx context.Context, galleryID int64) error {
	_, err := q.db.ExecContext(ctx, complete, galleryID)
	return err
}

const due = `-- name: Due :many
SELECT gallery_id, panda_id, failures FROM panda_enrichments
WHERE next_attempt_at <= ? ORDER BY next_attempt_at, gallery_id LIMIT ?
`

type DueParams struct {
	NextAttemptAt int64
	Limit         int64
}

type DueRow struct {
	GalleryID int64
	PandaID   int64
	Failures  int64
}

func (q *Queries) Due(ctx context.Context, arg DueParams) ([]DueRow, error) {
	rows, err := q.db.QueryContext(ctx, due, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueRow{}
	for rows.Next() {
		var i DueRow
		if err := rows.Scan(&i.GalleryID, &i.PandaID, &i.Failures); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueue = `-- name: Enqueue :exec
INSERT INTO panda_enrichments (gallery_id, panda_id) VALUES (?, ?)
`

type EnqueueParams struct {
	GalleryID int64
	PandaID   int64
}

func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) error {
	_, err := q.db.ExecContext(ctx, enqueue, arg.GalleryID, arg.PandaID)
	return err
}

const getPending = `-- name: GetPending :one
SELECT panda_id FROM panda_enrichments WHERE gallery_id = ?
`

func (q *Queries) GetPending(ctx context.Context, galleryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPending, galleryID)
	var panda_id int64
	err := row.Scan(&panda_id)
	return panda_id, err
}

const retry = `-- name: Retry :exec
UPDATE panda_enrichments SET next_attempt_at = ?, failures = ? WHERE gallery_id = ?
`

type RetryParams struct {
	NextAttemptAt int64
	Failures      int64
	GalleryID     int64
}

func (q *Queries) Retry(ctx context.Context, arg RetryParams) error {
	_, err := q.db.ExecContext(ctx, retry, arg.NextAttemptAt, arg.Failures, arg.GalleryID)
	return err
}
